<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Interfaces\MultiHtmlCraft.Interfaces.csproj" />
    <ProjectReference Include="..\MultiHtmlCraft.Core\MultiHtmlCraft.Core.csproj" />
  </ItemGroup>
	<PropertyGroup>
		<NoWarn>$(NoWarn);CS0618;SYSLIB8660;SYSLIB8060;CS8600;CS8604;CS8618;CS8601;CS8602;CS8629;CS8625;CS0164;CS0436;CS0428;IDE0090; IDE0017;IDE0300; IDE0020;IDE0019;IDE0220;IDE0059;IDE0079;IDE1006;IDE0028;IDE0031;IDE0044;IDE0018; CA2211; CA1840;CA1860;CA1806;CA1416;CS8622;CS8603;CS0649;CS0414;CS0169;CS0219;CS0162;CS0168</NoWarn>
		
	</PropertyGroup>
</Project>
