<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaXaml Remove="MultiHtmlCraft.AvaroniaControl\**" />
    <Compile Remove="MultiHtmlCraft.AvaroniaControl\**" />
    <EmbeddedResource Remove="MultiHtmlCraft.AvaroniaControl\**" />
    <None Remove="MultiHtmlCraft.AvaroniaControl\**" />
    <Folder Include="MultiHtmlCraft\MultiHtmlCraft\MultiHtmlCraft.Core\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.11" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    <PackageReference Include="NTextCat" Version="0.3.65" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MultiHtmlCraft\MultiHtmlCraft.AvaroniaControl\MultiHtmlCraft.AvaroniaControl.csproj" />
  </ItemGroup>
	<PropertyGroup>
		<NoWarn>$(NoWarn);CS1591;CS8618;CS8600:CS8602;CS8603;CS8604;CS8602;CS0219;CS0162;CS8603;CS8625;CS8625;CS8604;CS8602;CS860;CS8600;CS8640;CS8767;CS8601;CS0436;CS0414</NoWarn>
	</PropertyGroup>
	
</Project>
