<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<WarningLevel>0</WarningLevel>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MultiHtmlCraft\MultiHtmlCraft.Core\MultiHtmlCraft.Core.csproj" />
    <ProjectReference Include="..\MultiHtmlCraft\NilJsProcessor\NilJsProcessor.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="NiL.JS" Version="2.6.1700" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="js\" />
	</ItemGroup>

</Project>
